---
name: Build container images

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
      - "release-*"

jobs:
  build:
    name: build_${{ matrix.image.name }}
    if: github.repository == 'ramendr/ceph-volsync-plugin'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: bundle
            dockerfile: bundle.Dockerfile
            image_name: quay.io/ramendr/ceph-volsync-plugin-operator-bundle
            needs_go: true
            needs_docker_buildx: false
          - name: operator
            dockerfile: build/Containerfile.manager
            image_name: quay.io/ramendr/ceph-volsync-plugin-operator
            needs_go: false
            needs_docker_buildx: true
          - name: mover
            dockerfile: build/Containerfile.mover
            image_name: quay.io/ramendr/ceph-volsync-plugin-mover
            needs_go: false
            needs_docker_buildx: true
    steps:
      - name: Check out the repo
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5

      - name: Setup Golang
        if: matrix.image.needs_go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod

      - name: Set up QEMU
        if: matrix.image.needs_docker_buildx
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3

      - name: Set up Docker Buildx
        if: matrix.image.needs_docker_buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Generate image tag
        id: tag
        env:
          REF_NAME: ${{ github.ref_name }}
        run: |
          if [[ "${REF_NAME}" == release-* ]]; then
            version="${REF_NAME#release-}"
            tag="v${version}-latest"
            echo "Generated tag: $tag"
            echo "tag=$tag" >> "$GITHUB_OUTPUT"
          else
            tag="latest"
            echo "Generated tag: $tag"
            echo "tag=$tag" >> "$GITHUB_OUTPUT"
          fi

      - name: Generate the bundle contents
        if: matrix.image.name == 'bundle'
        run: make bundle

      - name: Login to quay.io
        if: github.event_name == 'push'
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: .
          file: ${{ matrix.image.dockerfile }}
          platforms: ${{ matrix.image.needs_docker_buildx && vars.BUILD_PLATFORMS || '' }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ matrix.image.image_name }}:${{ steps.tag.outputs.tag }}
